// Mock OSINT data adapter. Provides realistic demo data across all entity types.
// In production, replace with real API adapters (Shodan, Censys, NVD, etc.).

import {
  createHost, createDomain, createVulnerability, createCertificate, createThreat,
} from '../schema.js';

export const mockHosts = [
  createHost({
    id: 'host-01', ip: '130.91.71.10', hostname: 'drexel.edu',
    ports: [
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
    ],
    services: [
      { name: 'http', product: 'Apache httpd', version: '2.4.49', banner: 'Apache/2.4.49 (Unix)' },
    ],
    os: 'Linux 5.x', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-10T14:22:00Z', source: 'shodan', tags: ['web', 'production'],
  }),
  createHost({
    id: 'host-02', ip: '130.91.71.11', hostname: 'mail.drexel.edu',
    ports: [
      { port: 25, protocol: 'tcp', state: 'open', service: 'smtp' },
      { port: 587, protocol: 'tcp', state: 'open', service: 'submission' },
      { port: 993, protocol: 'tcp', state: 'open', service: 'imaps' },
    ],
    services: [
      { name: 'smtp', product: 'Postfix smtpd', version: '3.5.6', banner: '220 mail.drexel.edu ESMTP Postfix' },
    ],
    os: 'Linux 5.x', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-10T14:24:00Z', source: 'shodan', tags: ['mail', 'production'],
  }),
  createHost({
    id: 'host-03', ip: '130.91.71.12', hostname: 'vpn.drexel.edu',
    ports: [
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
      { port: 1194, protocol: 'udp', state: 'open', service: 'openvpn' },
    ],
    services: [
      { name: 'openvpn', product: 'OpenVPN', version: '2.5.3', banner: null },
    ],
    os: 'Linux 5.x', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-09T10:00:00Z', source: 'censys', tags: ['vpn', 'production'],
  }),
  createHost({
    id: 'host-04', ip: '130.91.71.13', hostname: 'ssh.drexel.edu',
    ports: [{ port: 22, protocol: 'tcp', state: 'open', service: 'ssh' }],
    services: [
      { name: 'ssh', product: 'OpenSSH', version: '8.4p1', banner: 'SSH-2.0-OpenSSH_8.4p1 Debian-5' },
    ],
    os: 'Debian GNU/Linux 11', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-10T08:30:00Z', source: 'shodan', tags: ['ssh', 'production'],
  }),
  createHost({
    id: 'host-05', ip: '130.91.71.14', hostname: 'db-internal.drexel.edu',
    ports: [{ port: 3306, protocol: 'tcp', state: 'open', service: 'mysql' }],
    services: [{ name: 'mysql', product: 'MySQL', version: '5.7.36', banner: null }],
    os: 'Linux 4.x', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-10T06:15:00Z', source: 'shodan', tags: ['database', 'exposed', 'high-risk'],
  }),
  createHost({
    id: 'host-06', ip: '130.91.71.15', hostname: 'ftp.drexel.edu',
    ports: [{ port: 21, protocol: 'tcp', state: 'open', service: 'ftp' }],
    services: [{ name: 'ftp', product: 'vsftpd', version: '3.0.3', banner: '220 (vsFTPd 3.0.3)' }],
    os: 'Linux 3.x', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-08T22:00:00Z', source: 'shodan', tags: ['ftp', 'legacy'],
  }),
  createHost({
    id: 'host-07', ip: '130.91.71.16', hostname: 'dev.drexel.edu',
    ports: [
      { port: 8080, protocol: 'tcp', state: 'open', service: 'http-proxy' },
      { port: 8443, protocol: 'tcp', state: 'open', service: 'https-alt' },
    ],
    services: [{ name: 'http', product: 'nginx', version: '1.18.0', banner: 'nginx/1.18.0' }],
    os: 'Ubuntu 20.04', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-07T18:45:00Z', source: 'censys', tags: ['development', 'non-standard-port'],
  }),
  createHost({
    id: 'host-08', ip: '130.91.71.17', hostname: 'portal.drexel.edu',
    ports: [
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
      { port: 8080, protocol: 'tcp', state: 'open', service: 'http-proxy' },
    ],
    services: [{ name: 'http', product: 'Apache Tomcat', version: '9.0.44', banner: null }],
    os: 'CentOS 7', country: 'US', asn: 'AS14434', org: 'Drexel University',
    lastSeen: '2025-05-10T12:00:00Z', source: 'shodan', tags: ['portal', 'production', 'java'],
  }),
];

export const mockDomains = [
  createDomain({
    id: 'domain-01', name: 'drexel.edu',
    records: [
      { type: 'A', value: '130.91.71.10', ttl: 300 },
      { type: 'NS', value: 'ns1.drexel.edu', ttl: 3600 },
      { type: 'NS', value: 'ns2.drexel.edu', ttl: 3600 },
      { type: 'MX', value: 'mail.drexel.edu', ttl: 3600 },
      { type: 'TXT', value: 'v=spf1 include:_spf.drexel.edu ~all', ttl: 3600 },
    ],
    registrar: 'MarkMonitor Inc.', created: '1988-04-20', expires: '2026-07-31',
    subdomains: ['mail', 'vpn', 'portal', 'learn', 'dev', 'ftp', 'ssh'],
    ips: ['130.91.71.10'], source: 'dns-recon', tags: ['apex', 'edu'],
  }),
  createDomain({
    id: 'domain-02', name: 'mail.drexel.edu',
    records: [
      { type: 'A', value: '130.91.71.11', ttl: 300 },
      { type: 'MX', value: 'mail.drexel.edu', ttl: 3600 },
    ],
    ips: ['130.91.71.11'], source: 'dns-recon', tags: ['subdomain', 'mail'],
  }),
  createDomain({
    id: 'domain-03', name: 'vpn.drexel.edu',
    records: [{ type: 'A', value: '130.91.71.12', ttl: 300 }],
    ips: ['130.91.71.12'], source: 'dns-recon', tags: ['subdomain', 'vpn'],
  }),
  createDomain({
    id: 'domain-04', name: 'learn.drexel.edu',
    records: [{ type: 'CNAME', value: 'drexel.blackboard.com', ttl: 300 }],
    ips: [], source: 'dns-recon', tags: ['subdomain', 'cname', 'third-party'],
  }),
  createDomain({
    id: 'domain-05', name: 'portal.drexel.edu',
    records: [{ type: 'A', value: '130.91.71.17', ttl: 300 }],
    ips: ['130.91.71.17'], source: 'dns-recon', tags: ['subdomain', 'portal'],
  }),
  createDomain({
    id: 'domain-06', name: 'dev.drexel.edu',
    records: [{ type: 'A', value: '130.91.71.16', ttl: 300 }],
    ips: ['130.91.71.16'], source: 'dns-recon', tags: ['subdomain', 'development'],
  }),
];

export const mockVulnerabilities = [
  createVulnerability({
    id: 'CVE-2021-41773',
    title: 'Apache HTTP Server Path Traversal / RCE',
    description: 'A flaw in path normalization in Apache HTTP Server 2.4.49 allows an attacker to use a path traversal attack to map URLs to files outside configured directories. With CGI scripts enabled, remote code execution is possible.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['Apache httpd 2.4.49'],
    published: '2021-10-05', modified: '2021-10-12',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-41773', 'https://httpd.apache.org/security/vulnerabilities_24.html'],
    cwe: 'CWE-22', source: 'nvd', tags: ['apache', 'rce', 'path-traversal'],
  }),
  createVulnerability({
    id: 'CVE-2021-42013',
    title: 'Apache HTTP Server Path Traversal Bypass (2.4.50)',
    description: 'The fix for CVE-2021-41773 in Apache HTTP Server 2.4.50 was insufficient. An attacker can still use path traversal to map URLs to files outside configured Alias-like directives, and achieve RCE with CGI enabled.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['Apache httpd 2.4.49', 'Apache httpd 2.4.50'],
    published: '2021-10-07', modified: '2021-10-20',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-42013'],
    cwe: 'CWE-22', source: 'nvd', tags: ['apache', 'rce', 'path-traversal'],
  }),
  createVulnerability({
    id: 'CVE-2021-44228',
    title: 'Log4Shell: Apache Log4j2 Remote Code Execution',
    description: 'Apache Log4j2 <=2.14.1 JNDI features do not protect against attacker-controlled LDAP endpoints. An attacker who can control log messages can execute arbitrary code loaded from LDAP servers.',
    severity: 'critical', cvss: 10.0,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    affectedProducts: ['Apache Log4j 2.0-beta9 through 2.14.1'],
    published: '2021-12-10', modified: '2022-01-04',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-44228', 'https://logging.apache.org/log4j/2.x/security.html'],
    cwe: 'CWE-917', source: 'nvd', tags: ['log4j', 'rce', 'java', 'critical'],
  }),
  createVulnerability({
    id: 'CVE-2022-22965',
    title: 'Spring4Shell: Spring Framework RCE via Data Binding',
    description: 'A Spring MVC or Spring WebFlux application running on JDK 9+ may be vulnerable to remote code execution via data binding. Affects Spring Framework 5.3.0-5.3.17 and 5.2.0-5.2.19.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['Spring Framework 5.3.0 to 5.3.17', 'Spring Framework 5.2.0 to 5.2.19'],
    published: '2022-04-01', modified: '2022-04-15',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-22965', 'https://spring.io/security/cve-2022-22965'],
    cwe: 'CWE-94', source: 'nvd', tags: ['spring', 'rce', 'java'],
  }),
  createVulnerability({
    id: 'CVE-2022-1292',
    title: 'OpenSSL c_rehash Script Command Injection RCE',
    description: 'The c_rehash script does not properly sanitize shell metacharacters to prevent command injection. On systems where it runs automatically, an attacker could execute arbitrary commands with the script\'s privileges.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['OpenSSL 1.0.2 < 1.0.2ze', 'OpenSSL 1.1.1 < 1.1.1o', 'OpenSSL 3.0 < 3.0.3'],
    published: '2022-05-03', modified: '2022-05-20',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-1292', 'https://www.openssl.org/news/secadv/20220503.txt'],
    cwe: 'CWE-78', source: 'nvd', tags: ['openssl', 'rce', 'command-injection'],
  }),
  createVulnerability({
    id: 'CVE-2019-11043',
    title: 'PHP-FPM Remote Code Execution via nginx',
    description: 'In certain nginx + PHP-FPM configurations, an attacker can cause FPM to write past allocated buffers into FCGI protocol data space, enabling remote code execution. Affected PHP versions 7.1.x < 7.1.33, 7.2.x < 7.2.24, 7.3.x < 7.3.11.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['PHP 7.1.x < 7.1.33', 'PHP 7.2.x < 7.2.24', 'PHP 7.3.x < 7.3.11', 'nginx'],
    published: '2019-10-28', modified: '2020-01-15',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2019-11043'],
    cwe: 'CWE-119', source: 'nvd', tags: ['php', 'nginx', 'rce'],
  }),
  createVulnerability({
    id: 'CVE-2022-22720',
    title: 'Apache HTTP Server Request Smuggling',
    description: 'Apache HTTP Server 2.4.52 and earlier fails to close inbound connection when errors are encountered discarding the request body, exposing the server to HTTP Request Smuggling attacks.',
    severity: 'high', cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    affectedProducts: ['Apache httpd 2.4.0 through 2.4.52'],
    published: '2022-03-14', modified: '2022-03-25',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-22720'],
    cwe: 'CWE-444', source: 'nvd', tags: ['apache', 'request-smuggling'],
  }),
  createVulnerability({
    id: 'CVE-2021-23017',
    title: 'nginx DNS Resolver Out-of-Bounds Write',
    description: 'A security issue in the nginx resolver allows an attacker able to forge UDP packets from the DNS server to cause a 1-byte memory overwrite, resulting in worker process crash or potential code execution.',
    severity: 'high', cvss: 7.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:L',
    affectedProducts: ['nginx 0.6.18 through 1.20.0'],
    published: '2021-05-25', modified: '2021-06-15',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-23017', 'https://nginx.org/en/security_advisories.html'],
    cwe: 'CWE-193', source: 'nvd', tags: ['nginx', 'memory-corruption'],
  }),
  createVulnerability({
    id: 'CVE-2022-0778',
    title: 'OpenSSL Infinite Loop Denial of Service',
    description: 'The BN_mod_sqrt() function contains a bug that can cause it to loop forever for non-prime moduli. This can be triggered remotely by connecting with a specially crafted certificate, causing a denial of service.',
    severity: 'high', cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H',
    affectedProducts: ['OpenSSL 1.0.2 < 1.0.2zd', 'OpenSSL 1.1.1 < 1.1.1n', 'OpenSSL 3.0 < 3.0.2'],
    published: '2022-03-15', modified: '2022-04-01',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-0778', 'https://www.openssl.org/news/secadv/20220315.txt'],
    cwe: 'CWE-835', source: 'nvd', tags: ['openssl', 'dos'],
  }),
  createVulnerability({
    id: 'CVE-2021-3156',
    title: 'sudo Heap-Based Buffer Overflow (Baron Samedit)',
    description: 'sudo before 1.9.5p2 has a heap-based buffer overflow allowing privilege escalation to root via "sudoedit -s" and a command-line argument ending with a single backslash character.',
    severity: 'high', cvss: 7.8,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['sudo 1.8.2 through 1.8.31p2', 'sudo 1.9.0 through 1.9.5p1'],
    published: '2021-01-26', modified: '2021-02-15',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-3156'],
    cwe: 'CWE-122', source: 'nvd', tags: ['sudo', 'privilege-escalation', 'local'],
  }),
  createVulnerability({
    id: 'CVE-2022-0847',
    title: 'Dirty Pipe: Linux Kernel Privilege Escalation',
    description: 'A flaw in the Linux kernel pipe buffer flags initialization allows an unprivileged local user to write to pages in the page cache backed by read-only files, enabling local privilege escalation.',
    severity: 'high', cvss: 7.8,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['Linux kernel 5.8 through 5.16.10'],
    published: '2022-03-07', modified: '2022-03-20',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-0847', 'https://dirtypipe.cm4all.com/'],
    cwe: 'CWE-909', source: 'nvd', tags: ['kernel', 'privilege-escalation', 'local'],
  }),
  createVulnerability({
    id: 'CVE-2022-21449',
    title: 'Java ECDSA Signature Verification Bypass (Psychic Signatures)',
    description: 'A vulnerability in Java SE ECDSA signature verification allows an unauthenticated attacker to completely bypass authentication or access controls using crafted zero-value signatures.',
    severity: 'high', cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    affectedProducts: ['Oracle Java SE 17.0.2 and earlier', 'Oracle GraalVM Enterprise Edition 21.3.2 and earlier'],
    published: '2022-04-19', modified: '2022-05-01',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-21449'],
    cwe: 'CWE-347', source: 'nvd', tags: ['java', 'crypto', 'authentication-bypass'],
  }),
  createVulnerability({
    id: 'CVE-2021-32785',
    title: 'vsftpd Null Pointer Dereference DoS',
    description: 'vsftpd 3.0.3 has a null pointer dereference that can allow a remote attacker to crash the vsftpd daemon, causing a denial of service.',
    severity: 'medium', cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    affectedProducts: ['vsftpd 3.0.3'],
    published: '2021-06-21', modified: '2021-07-01',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-32785'],
    cwe: 'CWE-476', source: 'nvd', tags: ['vsftpd', 'dos'],
  }),
  createVulnerability({
    id: 'CVE-2020-11022',
    title: 'jQuery Cross-Site Scripting (XSS)',
    description: 'In jQuery >= 1.2 and < 3.5.0, passing HTML containing <script> tags from untrusted sources to DOM manipulation methods may execute untrusted code. Affects jQuery 1.2.x through 3.4.x.',
    severity: 'medium', cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    affectedProducts: ['jQuery 1.2.x through 3.4.x'],
    published: '2020-04-29', modified: '2020-05-15',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2020-11022'],
    cwe: 'CWE-79', source: 'nvd', tags: ['jquery', 'xss', 'client-side'],
  }),
  createVulnerability({
    id: 'CVE-2021-3560',
    title: 'polkit Local Privilege Escalation',
    description: 'polkit could be tricked into bypassing credential checks for D-Bus requests, allowing an attacker to escalate privileges to root by exploiting a race condition in the authentication flow.',
    severity: 'high', cvss: 7.8,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['polkit < 0.119'],
    published: '2021-06-03', modified: '2021-06-20',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-3560'],
    cwe: 'CWE-754', source: 'nvd', tags: ['polkit', 'privilege-escalation', 'linux'],
  }),
  createVulnerability({
    id: 'CVE-2021-26084',
    title: 'Atlassian Confluence OGNL Injection RCE',
    description: 'An OGNL injection vulnerability in Atlassian Confluence Server and Data Center allows an unauthenticated attacker to execute arbitrary code via specially crafted requests.',
    severity: 'critical', cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    affectedProducts: ['Confluence Server < 6.13.23', 'Confluence Server 6.14.0 through 7.4.11'],
    published: '2021-08-25', modified: '2021-09-10',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-26084'],
    cwe: 'CWE-74', source: 'nvd', tags: ['confluence', 'rce', 'ognl'],
  }),
];

export const mockCertificates = [
  createCertificate({
    id: 'cert-01', subject: '*.drexel.edu', issuer: "Let's Encrypt",
    domains: ['*.drexel.edu', 'drexel.edu'],
    validFrom: '2025-02-15T00:00:00Z', validTo: '2025-08-13T23:59:59Z',
    algorithm: 'RSA 2048', fingerprint: 'A1:B2:C3:D4:E5:F6:01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB',
    serialNumber: '03:A1:5E:29:BF:C4:D2:7A:09:87:65:43:21:FE:DC:BA',
    source: 'censys', tags: ['wildcard', 'production'],
  }),
  createCertificate({
    id: 'cert-02', subject: 'mail.drexel.edu', issuer: "Let's Encrypt",
    domains: ['mail.drexel.edu'],
    validFrom: '2025-04-02T00:00:00Z', validTo: '2025-07-01T23:59:59Z',
    algorithm: 'RSA 2048', fingerprint: 'B2:C3:D4:E5:F6:07:12:34:56:78:9A:BC:DE:F0:12:34:56:78:9A:BC',
    source: 'censys', tags: ['mail', 'production'],
  }),
  createCertificate({
    id: 'cert-03', subject: 'vpn.drexel.edu', issuer: 'DigiCert Inc',
    domains: ['vpn.drexel.edu'],
    validFrom: '2024-12-01T00:00:00Z', validTo: '2025-11-30T23:59:59Z',
    algorithm: 'RSA 4096', fingerprint: 'C3:D4:E5:F6:07:18:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD',
    source: 'censys', tags: ['vpn', 'production'],
  }),
  createCertificate({
    id: 'cert-04', subject: 'dev.drexel.edu', issuer: 'Self-signed',
    domains: ['dev.drexel.edu'],
    validFrom: '2023-01-01T00:00:00Z', validTo: '2024-01-01T00:00:00Z',
    algorithm: 'RSA 2048', fingerprint: 'D4:E5:F6:07:18:29:34:56:78:9A:BC:DE:F0:12:34:56:78:9A:BC:DE',
    source: 'censys', tags: ['development', 'self-signed', 'expired'],
  }),
  createCertificate({
    id: 'cert-05', subject: 'portal.drexel.edu', issuer: 'Sectigo Limited',
    domains: ['portal.drexel.edu'],
    validFrom: '2024-11-18T00:00:00Z', validTo: '2025-06-06T23:59:59Z',
    algorithm: 'RSA 2048', fingerprint: 'E5:F6:07:18:29:3A:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF',
    source: 'censys', tags: ['portal', 'production'],
  }),
  createCertificate({
    id: 'cert-06', subject: 'learn.drexel.edu', issuer: "Let's Encrypt",
    domains: ['learn.drexel.edu'],
    validFrom: '2025-03-20T00:00:00Z', validTo: '2025-07-18T23:59:59Z',
    algorithm: 'RSA 2048', fingerprint: 'F6:07:18:29:3A:4B:56:78:9A:BC:DE:F0:12:34:56:78:9A:BC:DE:F0',
    source: 'censys', tags: ['learn', 'third-party'],
  }),
];

export const mockThreats = [
  createThreat({
    id: 'threat-01', category: 'scanner',
    title: 'SSH Brute Force Campaign',
    description: 'Multiple source IPs making high-volume SSH authentication attempts against ssh.drexel.edu (130.91.71.13). Pattern is consistent with automated credential stuffing.',
    severity: 'high',
    indicators: [
      { type: 'ip', value: '185.220.101.5' }, { type: 'ip', value: '185.220.101.47' },
      { type: 'ip', value: '193.32.162.88' }, { type: 'ip', value: '45.142.212.48' },
    ],
    references: ['https://www.abuseipdb.com/'],
    firstSeen: '2025-04-28T02:14:00Z', lastSeen: '2025-05-10T22:58:00Z',
    source: 'threat-feed', tags: ['ssh', 'brute-force', 'active'],
  }),
  createThreat({
    id: 'threat-02', category: 'c2',
    title: 'Log4Shell Exploitation Attempts (CVE-2021-44228)',
    description: 'Active exploitation attempts targeting Log4j2 JNDI injection vulnerability (CVE-2021-44228) observed against Drexel Java services. Payloads attempting callback to attacker-controlled LDAP servers.',
    severity: 'critical',
    indicators: [
      { type: 'ip', value: '162.247.74.200' },
      { type: 'domain', value: 'log4jexploit.xyz' },
      { type: 'url', value: 'ldap://162.247.74.200:1389/Exploit' },
    ],
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-44228'],
    firstSeen: '2025-04-15T08:30:00Z', lastSeen: '2025-05-09T16:22:00Z',
    source: 'ids-alert', tags: ['log4shell', 'exploitation', 'active', 'java'],
  }),
  createThreat({
    id: 'threat-03', category: 'phishing',
    title: 'Drexel University Credential Phishing Campaign',
    description: 'Typosquatting domains and lookalike email campaigns targeting Drexel University students and faculty. Fake portal login pages designed to harvest @drexel.edu credentials.',
    severity: 'high',
    indicators: [
      { type: 'domain', value: 'drexe1.edu' },
      { type: 'domain', value: 'drexel-portal.com' },
      { type: 'domain', value: 'drexeluniversity.net' },
      { type: 'ip', value: '91.108.4.234' },
    ],
    references: ['https://phishtank.org/'],
    firstSeen: '2025-03-01T00:00:00Z', lastSeen: '2025-05-08T12:00:00Z',
    source: 'threat-feed', tags: ['phishing', 'credential-theft', 'typosquatting'],
  }),
  createThreat({
    id: 'threat-04', category: 'scanner',
    title: 'Exposed MySQL Reconnaissance Activity',
    description: 'Automated scanning of the exposed MySQL port (3306) on db-internal.drexel.edu from known malicious infrastructure. Volume and timing suggest precursor to exploitation or data exfiltration.',
    severity: 'critical',
    indicators: [
      { type: 'ip', value: '5.188.206.26' },
      { type: 'ip', value: '198.54.117.197' },
      { type: 'ip', value: '185.156.73.54' },
    ],
    references: [],
    firstSeen: '2025-05-01T00:00:00Z', lastSeen: '2025-05-10T23:45:00Z',
    source: 'ids-alert', tags: ['mysql', 'database', 'scanning', 'active'],
  }),
  createThreat({
    id: 'threat-05', category: 'malware',
    title: 'Ransomware Precursor Activity Detected',
    description: 'Behavioral patterns consistent with ransomware staging: unusual SMB lateral movement, LSASS credential dumping attempts, and scheduled task creation detected across internal hosts.',
    severity: 'critical',
    indicators: [
      { type: 'hash', value: 'a3f2c1e4b5d6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2' },
      { type: 'hash', value: 'b4e3f2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3' },
    ],
    references: [],
    firstSeen: '2025-05-08T14:00:00Z', lastSeen: '2025-05-10T08:30:00Z',
    source: 'edr-alert', tags: ['ransomware', 'lateral-movement', 'active'],
  }),
  createThreat({
    id: 'threat-06', category: 'botnet',
    title: 'Legacy FTP Service Enumeration',
    description: 'Automated enumeration of ftp.drexel.edu (vsftpd 3.0.3) by botnet infrastructure. Anonymous login attempts and directory traversal probes indicate the legacy FTP service is actively targeted.',
    severity: 'medium',
    indicators: [
      { type: 'ip', value: '141.98.10.80' },
      { type: 'ip', value: '192.241.216.167' },
    ],
    references: [],
    firstSeen: '2025-04-10T00:00:00Z', lastSeen: '2025-05-09T20:00:00Z',
    source: 'threat-feed', tags: ['ftp', 'legacy', 'botnet', 'enumeration'],
  }),
];
